apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
   alb.ingress.kubernetes.io/healthcheck-path: /backend/health
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30003